# -*- coding: utf-8 -*-
"""imbalance data handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1phkcLodGU-Y0ze4IhNRlMCmJwGln5UyE
"""

import pandas as pd
import matplotlib.pyplot as plt
from imblearn.under_sampling import RandomUnderSampler as rus

data = pd.read_csv('https://raw.githubusercontent.com/dataprofessor/data/master/hcv_classification.csv', index_col=False)

data.head()

x = data.iloc[:,:-1]
y = data.iloc[:,-1]

classes_count = y.value_counts()
classes_count[0]/classes_count[1] # Imbalance percentage

classes_count.plot(kind='pie',autopct='%.0f%%')
plt.legend()

model = rus(sampling_strategy=1)
x_balance , y_balance = model.fit_resample(x,y)

x_balance

balance_classes = y_balance.value_counts()
balance_classes[0]/balance_classes[1] # balanc classes

balance_classes.plot(kind='pie',autopct='%.0f%%')
plt.legend()

balance_data = pd.DataFrame(x_balance.join(y_balance))

balance_data.head()