# -*- coding: utf-8 -*-
"""Isolation Tree-outlier detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OgIeCAxeITUO5wghls_9nBkhNseh2tRB
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
import matplotlib.pyplot as plt

data = pd.read_csv('creditcard.csv')

data.dropna(axis=1,inplace=True)
data.head()

data.info()

data.isna().sum() # algorithm is not robust against nan data and the dataset must be without these values

anomaly_features = ['V1','V2'	,'V7'	,'V9'	,'V15'	,'V18'	,'V20'	,'V22']

If_model = IsolationForest(contamination=0.1)

If_model.fit(data[anomaly_features])

data['anomaly_scores'] = If_model.decision_function(data[anomaly_features])
data.head()

data['anomaly'] = If_model.predict(data[anomaly_features]) # anomaly < 0 = outlier or anomaly
data.head()

