# -*- coding: utf-8 -*-
"""Time series with XGBoost ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKDX_O6T9OJsHFWSL8l-iG5Yl-7pYRSi
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBRegressor as xgbr
from sklearn.metrics import mean_squared_error as mse

"""# Data loading and Visualization"""

data = pd.read_csv('PJME_hourly.csv',index_col='Datetime')
data.index = pd.to_datetime(data.index)

data.index

data.head()

data.plot(title='Energy Use',figsize=(15,5),style='.')
plt.show()

data['Hour'] = data.index.hour
data['Days'] = data.index.dayofweek
data['Quarter'] = data.index.quarter
data['Month'] = data.index.month
data['year'] = data.index.year
data['Dayofyear'] = data.index.dayofyear

train = data.iloc[:100000,:]
test = data.iloc[100000:,:]
x_features = ['Hour','Days','Quarter','Month','year','Dayofyear']
y_features = ['PJME_MW']

x_train =train[x_features]
y_train = train[y_features]
x_test =test[x_features]
y_test = test[y_features]

train.plot(title='Train Energy Use',figsize=(8,6),style='.')
plt.legend(loc='upper right')
plt.show()

test.plot(title='Test Energy Use',figsize=(8,6),style='.')
plt.legend(loc='upper right')
plt.show()

data

sns.boxplot(data=data,x='year',y='PJME_MW')

"""# Model"""

model = xgbr(n_estimators=500,early_stopping_rounds=10,learning_rate=0.001)

model.fit(x_train,y_train,eval_set=[(x_train,y_train),(x_test,y_test)])

rates = pd.DataFrame(data=model.feature_importances_ ,index=model.feature_names_in_,columns=['importance of features ']) ## feature selection
rates

rates['importance of features '].plot(kind='hist', bins=20, title='importance of features ')
plt.gca().spines[['top', 'right',]].set_visible(False)

rates.sort_values('importance of features ').plot(kind='barh',title='importance of features')
plt.show()

y_pred = model.predict(x_test)

np.sqrt(mse(y_test,y_pred))

